name: visual-regression

on:
  pull_request:
    branches:
    - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependancies
        run: npm install

      - name: Start client
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npm run start -- --env.ACCESS_TOKEN=$ACCESS_TOKEN & npx wait-on http://localhost:3000

      - name: Run tests
        run: npm run visual-regression
