# This is a basic workflow to help you get started with Actions

name: visual-regression

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependancies
        run: npm install

      - name: Start client
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          IMAGE_DOMAIN: ${{ secrets.IMAGE_DOMAIN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
        run: npm run start -- --env.ACCESS_TOKEN=$ACCESS_TOKEN --env.ENVIRONMENT=$ENVIRONMENT  --env.IMAGE_DOMAIN=$IMAGE_DOMAIN --env.SPACE_ID=$SPACE_ID & npx wait-on http://localhost:3000

      # Runs a single command using the runners shell
      - name: Run tests
        run: npm run visual-regression
